# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
# source: client.sql
import pydantic
from typing import Optional
import uuid

import sqlalchemy
import sqlalchemy.ext.asyncio

from db import models


CREATE_CLIENT = """-- name: create_client \\:one
insert into client (email, password_hash, name, surname, image_url)
values (:p1, :p2, :p3, :p4, :p5)
returning id, name, surname, email, password_hash, image_url
"""


class CreateClientParams(pydantic.BaseModel):
    email: str
    password_hash: str
    name: str
    surname: str
    image_url: str


DELETE_CLIENT = """-- name: delete_client \\:exec
delete from client
where id = :p1
returning id
"""


GET_CLIENT_BY_EMAIL = """-- name: get_client_by_email \\:one
select id, name, surname, email, password_hash, image_url from client
where email = :p1
"""


GET_CLIENT_BY_ID = """-- name: get_client_by_id \\:one
select id, name, surname, email, password_hash, image_url from client
where id = :p1
"""


UPDATE_CLIENT = """-- name: update_client \\:one
update client
set
    name   = coalesce(:p2, name),
    surname  = coalesce(:p3, surname),
    image_url  = coalesce(:p4, image_url)
where
    id = :p1
returning id, name, surname, email, password_hash, image_url
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_client(self, arg: CreateClientParams) -> Optional[models.Client]:
        row = self._conn.execute(sqlalchemy.text(CREATE_CLIENT), {
            "p1": arg.email,
            "p2": arg.password_hash,
            "p3": arg.name,
            "p4": arg.surname,
            "p5": arg.image_url,
        }).first()
        if row is None:
            return None
        return models.Client(
            id=row[0],
            name=row[1],
            surname=row[2],
            email=row[3],
            password_hash=row[4],
            image_url=row[5],
        )

    def delete_client(self, *, id: uuid.UUID) -> None:
        self._conn.execute(sqlalchemy.text(DELETE_CLIENT), {"p1": id})

    def get_client_by_email(self, *, email: str) -> Optional[models.Client]:
        row = self._conn.execute(sqlalchemy.text(GET_CLIENT_BY_EMAIL), {"p1": email}).first()
        if row is None:
            return None
        return models.Client(
            id=row[0],
            name=row[1],
            surname=row[2],
            email=row[3],
            password_hash=row[4],
            image_url=row[5],
        )

    def get_client_by_id(self, *, id: uuid.UUID) -> Optional[models.Client]:
        row = self._conn.execute(sqlalchemy.text(GET_CLIENT_BY_ID), {"p1": id}).first()
        if row is None:
            return None
        return models.Client(
            id=row[0],
            name=row[1],
            surname=row[2],
            email=row[3],
            password_hash=row[4],
            image_url=row[5],
        )

    def update_client(self, *, id: uuid.UUID, name: Optional[str], surname: Optional[str], image_url: Optional[str]) -> Optional[models.Client]:
        row = self._conn.execute(sqlalchemy.text(UPDATE_CLIENT), {
            "p1": id,
            "p2": name,
            "p3": surname,
            "p4": image_url,
        }).first()
        if row is None:
            return None
        return models.Client(
            id=row[0],
            name=row[1],
            surname=row[2],
            email=row[3],
            password_hash=row[4],
            image_url=row[5],
        )


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_client(self, arg: CreateClientParams) -> Optional[models.Client]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_CLIENT), {
            "p1": arg.email,
            "p2": arg.password_hash,
            "p3": arg.name,
            "p4": arg.surname,
            "p5": arg.image_url,
        })).first()
        if row is None:
            return None
        return models.Client(
            id=row[0],
            name=row[1],
            surname=row[2],
            email=row[3],
            password_hash=row[4],
            image_url=row[5],
        )

    async def delete_client(self, *, id: uuid.UUID) -> None:
        await self._conn.execute(sqlalchemy.text(DELETE_CLIENT), {"p1": id})

    async def get_client_by_email(self, *, email: str) -> Optional[models.Client]:
        row = (await self._conn.execute(sqlalchemy.text(GET_CLIENT_BY_EMAIL), {"p1": email})).first()
        if row is None:
            return None
        return models.Client(
            id=row[0],
            name=row[1],
            surname=row[2],
            email=row[3],
            password_hash=row[4],
            image_url=row[5],
        )

    async def get_client_by_id(self, *, id: uuid.UUID) -> Optional[models.Client]:
        row = (await self._conn.execute(sqlalchemy.text(GET_CLIENT_BY_ID), {"p1": id})).first()
        if row is None:
            return None
        return models.Client(
            id=row[0],
            name=row[1],
            surname=row[2],
            email=row[3],
            password_hash=row[4],
            image_url=row[5],
        )

    async def update_client(self, *, id: uuid.UUID, name: Optional[str], surname: Optional[str], image_url: Optional[str]) -> Optional[models.Client]:
        row = (await self._conn.execute(sqlalchemy.text(UPDATE_CLIENT), {
            "p1": id,
            "p2": name,
            "p3": surname,
            "p4": image_url,
        })).first()
        if row is None:
            return None
        return models.Client(
            id=row[0],
            name=row[1],
            surname=row[2],
            email=row[3],
            password_hash=row[4],
            image_url=row[5],
        )
