# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
# source: event.sql
import pydantic
from typing import AsyncIterator, Iterator, Optional
import uuid

import sqlalchemy
import sqlalchemy.ext.asyncio

from db import models


CREATE_EVENT = """-- name: create_event \\:one
insert into event (name, info, image_url, points, stand_id)
values (:p1, :p2, :p3, :p4, :p5)
returning id, name, info, image_url, points, stand_id
"""


class CreateEventParams(pydantic.BaseModel):
    name: str
    info: str
    image_url: str
    points: int
    stand_id: Optional[uuid.UUID]


DELETE_EVENT = """-- name: delete_event \\:exec
delete from event
where id = :p1
returning id
"""


GET_ALL_EVENTS = """-- name: get_all_events \\:many
select id, name, info, image_url, points, stand_id from event
"""


GET_EVENT_BY_ID = """-- name: get_event_by_id \\:one
select id, name, info, image_url, points, stand_id from event
where id = :p1
"""


UPDATE_EVENT = """-- name: update_event \\:one
update event
set
    name = coalesce(:p2, name),
    info = coalesce(:p3, info),
    image_url = coalesce(:p4, image_url),
    points = coalesce(:p5, points),
    stand_id = coalesce(:p6, stand_id)
where
    id = :p1
returning id, name, info, image_url, points, stand_id
"""


class UpdateEventParams(pydantic.BaseModel):
    id: uuid.UUID
    name: Optional[str]
    info: Optional[str]
    image_url: Optional[str]
    points: Optional[int]
    stand_id: Optional[uuid.UUID]


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_event(self, arg: CreateEventParams) -> Optional[models.Event]:
        row = self._conn.execute(sqlalchemy.text(CREATE_EVENT), {
            "p1": arg.name,
            "p2": arg.info,
            "p3": arg.image_url,
            "p4": arg.points,
            "p5": arg.stand_id,
        }).first()
        if row is None:
            return None
        return models.Event(
            id=row[0],
            name=row[1],
            info=row[2],
            image_url=row[3],
            points=row[4],
            stand_id=row[5],
        )

    def delete_event(self, *, id: uuid.UUID) -> None:
        self._conn.execute(sqlalchemy.text(DELETE_EVENT), {"p1": id})

    def get_all_events(self) -> Iterator[models.Event]:
        result = self._conn.execute(sqlalchemy.text(GET_ALL_EVENTS))
        for row in result:
            yield models.Event(
                id=row[0],
                name=row[1],
                info=row[2],
                image_url=row[3],
                points=row[4],
                stand_id=row[5],
            )

    def get_event_by_id(self, *, id: uuid.UUID) -> Optional[models.Event]:
        row = self._conn.execute(sqlalchemy.text(GET_EVENT_BY_ID), {"p1": id}).first()
        if row is None:
            return None
        return models.Event(
            id=row[0],
            name=row[1],
            info=row[2],
            image_url=row[3],
            points=row[4],
            stand_id=row[5],
        )

    def update_event(self, arg: UpdateEventParams) -> Optional[models.Event]:
        row = self._conn.execute(sqlalchemy.text(UPDATE_EVENT), {
            "p1": arg.id,
            "p2": arg.name,
            "p3": arg.info,
            "p4": arg.image_url,
            "p5": arg.points,
            "p6": arg.stand_id,
        }).first()
        if row is None:
            return None
        return models.Event(
            id=row[0],
            name=row[1],
            info=row[2],
            image_url=row[3],
            points=row[4],
            stand_id=row[5],
        )


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_event(self, arg: CreateEventParams) -> Optional[models.Event]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_EVENT), {
            "p1": arg.name,
            "p2": arg.info,
            "p3": arg.image_url,
            "p4": arg.points,
            "p5": arg.stand_id,
        })).first()
        if row is None:
            return None
        return models.Event(
            id=row[0],
            name=row[1],
            info=row[2],
            image_url=row[3],
            points=row[4],
            stand_id=row[5],
        )

    async def delete_event(self, *, id: uuid.UUID) -> None:
        await self._conn.execute(sqlalchemy.text(DELETE_EVENT), {"p1": id})

    async def get_all_events(self) -> AsyncIterator[models.Event]:
        result = await self._conn.stream(sqlalchemy.text(GET_ALL_EVENTS))
        async for row in result:
            yield models.Event(
                id=row[0],
                name=row[1],
                info=row[2],
                image_url=row[3],
                points=row[4],
                stand_id=row[5],
            )

    async def get_event_by_id(self, *, id: uuid.UUID) -> Optional[models.Event]:
        row = (await self._conn.execute(sqlalchemy.text(GET_EVENT_BY_ID), {"p1": id})).first()
        if row is None:
            return None
        return models.Event(
            id=row[0],
            name=row[1],
            info=row[2],
            image_url=row[3],
            points=row[4],
            stand_id=row[5],
        )

    async def update_event(self, arg: UpdateEventParams) -> Optional[models.Event]:
        row = (await self._conn.execute(sqlalchemy.text(UPDATE_EVENT), {
            "p1": arg.id,
            "p2": arg.name,
            "p3": arg.info,
            "p4": arg.image_url,
            "p5": arg.points,
            "p6": arg.stand_id,
        })).first()
        if row is None:
            return None
        return models.Event(
            id=row[0],
            name=row[1],
            info=row[2],
            image_url=row[3],
            points=row[4],
            stand_id=row[5],
        )
