# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
import pydantic
from typing import Optional
import uuid


class ActiveEvent(pydantic.BaseModel):
    user_id: uuid.UUID
    event_id: uuid.UUID
    total_points: int


class Client(pydantic.BaseModel):
    id: uuid.UUID
    name: str
    surname: str
    email: str
    password_hash: str
    image_url: str
    tg_username: Optional[str]


class Event(pydantic.BaseModel):
    id: uuid.UUID
    name: str
    info: str
    image_url: str
    points: int


class Merch(pydantic.BaseModel):
    id: uuid.UUID
    name: str
    info: str
    image_url: str
    points_needed: int
