# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
import datetime
import pydantic
from typing import Optional
import uuid


class Analytic(pydantic.BaseModel):
    id: uuid.UUID
    user_id: Optional[uuid.UUID]
    stand_id: Optional[uuid.UUID]
    time: datetime.datetime


class Client(pydantic.BaseModel):
    id: uuid.UUID
    name: str
    surname: str
    email: str
    password_hash: str
    image_url: str
    tg_username: str


class Event(pydantic.BaseModel):
    id: uuid.UUID
    name: str
    info: str
    image_url: str
    points: int
    stand_id: Optional[uuid.UUID]


class Merch(pydantic.BaseModel):
    id: uuid.UUID
    name: str
    info: str
    image_url: str
    points_needed: int


class Point(pydantic.BaseModel):
    user_id: uuid.UUID
    total_points: int


class Stand(pydantic.BaseModel):
    id: uuid.UUID
    name: str
    info: str
    location: str
    image_url: str
