# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
# source: stand.sql
import pydantic
from typing import AsyncIterator, Iterator, Optional
import uuid

import sqlalchemy
import sqlalchemy.ext.asyncio

from db import models


CREATE_STAND = """-- name: create_stand \\:one
insert into stand (name, info, location, image_url)
values (:p1, :p2, :p3, :p4)
returning id, name, info, location, image_url
"""


DELETE_STAND = """-- name: delete_stand \\:exec
delete from stand
where id = :p1
returning id
"""


GET_ALL_STANDS = """-- name: get_all_stands \\:many
select id, name, info, location, image_url from stand
"""


GET_STAND_BY_ID = """-- name: get_stand_by_id \\:one
select id, name, info, location, image_url from stand
where id = :p1
"""


UPDATE_STAND = """-- name: update_stand \\:one
update stand
set
    name = coalesce(:p2, name),
    info = coalesce(:p3, info),
    location = coalesce(:p4, location),
    image_url = coalesce(:p5, image_url)
where
    id = :p1
returning id, name, info, location, image_url
"""


class UpdateStandParams(pydantic.BaseModel):
    id: uuid.UUID
    name: Optional[str]
    info: Optional[str]
    location: Optional[str]
    image_url: Optional[str]


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_stand(self, *, name: str, info: str, location: str, image_url: str) -> Optional[models.Stand]:
        row = self._conn.execute(sqlalchemy.text(CREATE_STAND), {
            "p1": name,
            "p2": info,
            "p3": location,
            "p4": image_url,
        }).first()
        if row is None:
            return None
        return models.Stand(
            id=row[0],
            name=row[1],
            info=row[2],
            location=row[3],
            image_url=row[4],
        )

    def delete_stand(self, *, id: uuid.UUID) -> None:
        self._conn.execute(sqlalchemy.text(DELETE_STAND), {"p1": id})

    def get_all_stands(self) -> Iterator[models.Stand]:
        result = self._conn.execute(sqlalchemy.text(GET_ALL_STANDS))
        for row in result:
            yield models.Stand(
                id=row[0],
                name=row[1],
                info=row[2],
                location=row[3],
                image_url=row[4],
            )

    def get_stand_by_id(self, *, id: uuid.UUID) -> Optional[models.Stand]:
        row = self._conn.execute(sqlalchemy.text(GET_STAND_BY_ID), {"p1": id}).first()
        if row is None:
            return None
        return models.Stand(
            id=row[0],
            name=row[1],
            info=row[2],
            location=row[3],
            image_url=row[4],
        )

    def update_stand(self, arg: UpdateStandParams) -> Optional[models.Stand]:
        row = self._conn.execute(sqlalchemy.text(UPDATE_STAND), {
            "p1": arg.id,
            "p2": arg.name,
            "p3": arg.info,
            "p4": arg.location,
            "p5": arg.image_url,
        }).first()
        if row is None:
            return None
        return models.Stand(
            id=row[0],
            name=row[1],
            info=row[2],
            location=row[3],
            image_url=row[4],
        )


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_stand(self, *, name: str, info: str, location: str, image_url: str) -> Optional[models.Stand]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_STAND), {
            "p1": name,
            "p2": info,
            "p3": location,
            "p4": image_url,
        })).first()
        if row is None:
            return None
        return models.Stand(
            id=row[0],
            name=row[1],
            info=row[2],
            location=row[3],
            image_url=row[4],
        )

    async def delete_stand(self, *, id: uuid.UUID) -> None:
        await self._conn.execute(sqlalchemy.text(DELETE_STAND), {"p1": id})

    async def get_all_stands(self) -> AsyncIterator[models.Stand]:
        result = await self._conn.stream(sqlalchemy.text(GET_ALL_STANDS))
        async for row in result:
            yield models.Stand(
                id=row[0],
                name=row[1],
                info=row[2],
                location=row[3],
                image_url=row[4],
            )

    async def get_stand_by_id(self, *, id: uuid.UUID) -> Optional[models.Stand]:
        row = (await self._conn.execute(sqlalchemy.text(GET_STAND_BY_ID), {"p1": id})).first()
        if row is None:
            return None
        return models.Stand(
            id=row[0],
            name=row[1],
            info=row[2],
            location=row[3],
            image_url=row[4],
        )

    async def update_stand(self, arg: UpdateStandParams) -> Optional[models.Stand]:
        row = (await self._conn.execute(sqlalchemy.text(UPDATE_STAND), {
            "p1": arg.id,
            "p2": arg.name,
            "p3": arg.info,
            "p4": arg.location,
            "p5": arg.image_url,
        })).first()
        if row is None:
            return None
        return models.Stand(
            id=row[0],
            name=row[1],
            info=row[2],
            location=row[3],
            image_url=row[4],
        )
